import type { Metadata } from "next";
import { InformationPage } from "../InformationPage";

export const metadata: Metadata = { title: "Privacy Policy — Kingdom Within", description: "How Kingdom Within handles wallet, source-text, blockchain, and IPFS data." };

export default function PrivacyPage() {
  return <InformationPage code="P" eyebrow="PRIVACY POLICY" title={<>Private by restraint.<br /><em>Public by design.</em></>} intro="This policy explains what the instrument processes, what becomes permanently public when you mint, and the choices available to you." sections={[
    { title: "Who this policy covers", content: <><p>The House of Joshi (“we,” “us,” or “our”) operates Kingdom Within and the Malkuta Protocol interface. This policy applies to your use of this website. Wallets, Base, IPFS gateways, Pinata, Reown, and other third-party services apply their own policies to their processing.</p></> },
    { title: "Data processed before minting", content: <><p>Text analysis and mandala rendering occur in your browser. We do not intentionally collect your name, email address, phone number, or private wallet keys. Never submit a seed phrase or private key.</p><p>When you connect a wallet, technical providers may process wallet address, IP address, device information, connection metadata, and encrypted relay traffic. Review <a href="https://reown.com/privacy-policy" target="_blank" rel="noreferrer">Reown’s Privacy Policy ↗</a>.</p></> },
    { title: "Data processed for canonical minting", content: <><p>To prepare a mint, the service receives your public wallet address, source text, mapping mode, timestamp, and short-lived signed authorization. It generates the SVG, metadata manifest, content hash, and IPFS URIs needed for the transaction.</p></> },
    { title: "Public and permanent data", content: <><p>Minted source text, artwork, metadata attributes, wallet address, token ID, transaction data, protocol version, epoch, timestamp, and content hash may be publicly accessible through Base and IPFS. Public blockchain data cannot generally be corrected or erased by us. Do not mint confidential, personal, unlawful, or third-party-sensitive text.</p></> },
    { title: "How data is used", content: <><p>We use data to operate the composer, authorize uploads, pin canonical artifacts, submit or display provenance, prevent misuse, diagnose failures, secure the service, comply with law, and produce aggregate Epoch statistics from public mint records.</p></> },
    { title: "Service providers and disclosures", content: <><p>Data may be processed by infrastructure needed to provide the service, including Reown for wallet connectivity, Base and RPC providers for blockchain access, and Pinata/IPFS for public artifact storage. Review <a href="https://pinata.cloud/terms" target="_blank" rel="noreferrer">Pinata’s terms and privacy information ↗</a> and <a href="https://docs.base.org/privacy-policy" target="_blank" rel="noreferrer">Base’s Privacy Policy ↗</a>. We may also disclose information when legally required or necessary to protect rights and security.</p></> },
    { title: "Retention and security", content: <><p>Short-lived authorization signatures are used to process uploads. Operational records may be retained only as reasonably needed for security, troubleshooting, compliance, and service operation. On-chain and public IPFS records may persist indefinitely. No electronic system is completely secure.</p></> },
    { title: "Your choices and rights", content: <><p>You can use the local composer without minting, decline wallet connection, disconnect through your wallet, and avoid submitting personal information. Depending on applicable law, you may have rights to access, correct, object to, restrict, or delete off-chain personal data we control. These rights cannot rewrite Base or public IPFS records.</p></> },
    { title: "Children, transfers, and changes", content: <><p>The service is not directed to children, and minting is limited to adults legally able to enter a binding agreement. Providers may process data in multiple countries. We may update this policy as the service or law changes; the date above identifies the current version.</p></> },
  ]} />;
}
