import type { Metadata } from "next";
import { InformationPage } from "../InformationPage";

export const metadata: Metadata = { title: "Terms and Conditions — Kingdom Within", description: "Terms governing use of Kingdom Within and the Malkuta Protocol." };

export default function TermsPage() {
  return <InformationPage code="T" eyebrow="TERMS AND CONDITIONS" title={<>Sovereignty requires<br /><em>clear boundaries.</em></>} intro="By accessing the interface, connecting a wallet, or minting, you agree to these terms. If you do not agree, do not use the service." sections={[
    { title: "Eligibility and acceptance", content: <><p>You must be at least 18 years old, have legal capacity to contract, and be permitted to use blockchain services where you live. You act for yourself unless authorized to bind another person or entity.</p></> },
    { title: "The service", content: <><p>Kingdom Within provides deterministic text analysis, artifact generation, public IPFS packaging, Base mainnet minting, provenance verification, collection display, and Epoch statistics. We may maintain, update, suspend, or discontinue interface features without changing provenance already recorded on-chain.</p></> },
    { title: "Wallet and transaction responsibility", content: <><p>You control your wallet and are responsible for its security, network selection, transaction review, taxes, gas, and all activity authorized with it. We cannot recover keys, reverse Base transactions, or restore assets sent to an incorrect address.</p></> },
    { title: "Your source text and permissions", content: <><p>You retain whatever rights you lawfully hold in submitted text. You represent that you may lawfully use and permanently publish it and that it does not infringe privacy, copyright, trademark, publicity, or other rights. Public-domain scripture remains public domain. Do not submit secrets, personal data, hateful abuse, malware, illegal content, or material you are not entitled to publish.</p></> },
    { title: "Token and artwork rights", content: <><p>Owning a token means owning that blockchain token, not the Malkuta Protocol, Kingdom Within brand, trademarks, contract code, or underlying third-party text rights. Unless a separate written license says otherwise, the holder receives a worldwide, non-exclusive right to display the associated canonical artwork for personal, non-commercial purposes while they own the token.</p></> },
    { title: "Prices, royalties, and taxes", content: <><p>Mint price is the active epoch price shown by the contract and wallet confirmation. Prices may change for future transactions. Base gas is separate. The contract signals a 7% secondary-sale royalty through ERC-2981, but marketplaces may not enforce it. You are responsible for taxes and reporting applicable to you.</p></> },
    { title: "Prohibited conduct", content: <><p>You may not misuse uploads, evade limits, interfere with the service, probe for vulnerabilities without authorization, impersonate others, manipulate collection statistics, violate sanctions or law, infringe rights, or use the service to facilitate fraud, money laundering, or harmful activity.</p></> },
    { title: "Third-party systems", content: <><p>Wallets, Base, RPC services, Reown, IPFS, Pinata, explorers, and marketplaces are independent services. Their availability, security, policies, and decisions are outside our control and may affect your experience. Base’s current terms are available in its <a href="https://docs.base.org/terms-of-service" target="_blank" rel="noreferrer">official documentation ↗</a>.</p></> },
    { title: "No warranties or investment promise", content: <><p>To the fullest extent permitted by law, the interface and protocol are provided “as is” and “as available.” We do not promise uninterrupted access, error-free code, permanent gateway availability, market liquidity, resale value, profit, or fitness for a particular purpose. NFTs are not offered as securities, investments, deposits, or financial advice.</p></> },
    { title: "Liability and indemnity", content: <><p>To the fullest extent permitted by law, we are not liable for indirect, incidental, special, consequential, exemplary, or lost-value damages arising from wallet compromise, user error, third-party systems, blockchain conditions, content, or market activity. You agree to be responsible for claims caused by your unlawful content, breach of these terms, or misuse of the service. Rights that cannot lawfully be excluded remain in force.</p></> },
    { title: "Changes and disputes", content: <><p>We may update these terms prospectively by posting a revised date. Continued use after an update constitutes acceptance where permitted by law. Before formal proceedings, the parties should attempt good-faith informal resolution. Mandatory consumer rights and legally required venues are not waived.</p></> },
  ]} />;
}
